import index from '../content/lessons.index.json'
import type { Lang, Localized } from './i18n'
import { unitOrder } from './units'

/** A video embedded at the end of a lesson, per language. */
export interface LessonVideo {
  title: string
  /** The id from the YouTube URL: youtube.com/watch?v=XXXXXXXXXXX */
  youtubeId: string
  /** Optional: jump straight to a timestamp, in seconds. */
  start?: number
}

/** An outside link shown under «للاستزادة» / “Go deeper”, per language. */
export interface LessonResource {
  title: string
  url: string
  /** One short line saying why this link is worth opening. */
  note?: string
}

/** The words of one language's lesson file: everything that is *language*. */
export interface LessonWords {
  title: string
  /** One sentence a newcomer understands, shown on the card and under the title. */
  description: string
  /** 2 to 4 short keywords shown on the lesson card. */
  tags?: string[]
  videos?: LessonVideo[]
  resources?: LessonResource[]
}

/**
 * A lesson without its bodies.
 *
 * One lesson, two languages: the structural fields (unit, order, minutes,
 * emoji) exist once, taken from the Arabic file, which is canonical; the words
 * exist per language. The bodies live in src/lib/lesson-content.ts, imported
 * only by the routes that actually render them; see that file for why.
 */
export interface Lesson extends Localized<LessonWords> {
  /** URL segment, taken from the file name: from-nothing.md → "from-nothing" */
  slug: string
  /** Which unit it belongs to. Must match an `id` in src/content/units.json. */
  unit: string
  /** Position inside the whole curriculum. Lower comes first. */
  order: number
  /** Rough reading time in minutes, used to set expectations on the card. */
  minutes: number
  emoji: string
}

/**
 * Every lesson, in curriculum order (by unit first, then by `order`).
 *
 * Generated by `npm run content:build` from the frontmatter of every pair of
 * files in src/content/lessons/{ar,en}/, which runs before both `dev` and
 * `build`. Adding a lesson is still just adding two files.
 */
export const lessons: Lesson[] = (index as Lesson[])
  .slice()
  .sort((a, b) => unitOrder(a.unit) - unitOrder(b.unit) || a.order - b.order)

const BY_SLUG = new Map(lessons.map((lesson) => [lesson.slug, lesson]))

export function getLesson(slug: string): Lesson | undefined {
  return BY_SLUG.get(slug)
}

/** The `{title, description, …}` of one language of a lesson. */
export function lessonWords(lesson: Lesson, lang: Lang): LessonWords {
  return lesson[lang]
}

/** Lessons of one unit, in order. */
export function lessonsOfUnit(unitId: string): Lesson[] {
  return lessons.filter((lesson) => lesson.unit === unitId)
}

/** The lesson before and after this one, for the previous/next links. */
export function neighbours(slug: string): { prev?: Lesson; next?: Lesson } {
  const index = lessons.findIndex((lesson) => lesson.slug === slug)
  if (index === -1) return {}
  return { prev: lessons[index - 1], next: lessons[index + 1] }
}
